# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_frame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_frame.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11video_frame.proto\"X\n\x0c\x46rameRequest\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x04 \x01(\x05\x12\x0f\n\x07isColor\x18\x05 \x01(\x08\"\x1b\n\nFrameReply\x12\r\n\x05reply\x18\x01 \x01(\x05\x32\x36\n\nVideoFrame\x12(\n\x04Send\x12\r.FrameRequest\x1a\x0b.FrameReply\"\x00(\x01\x30\x01\x62\x06proto3'
)




_FRAMEREQUEST = _descriptor.Descriptor(
  name='FrameRequest',
  full_name='FrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='FrameRequest.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='FrameRequest.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='FrameRequest.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fps', full_name='FrameRequest.fps', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isColor', full_name='FrameRequest.isColor', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=109,
)


_FRAMEREPLY = _descriptor.Descriptor(
  name='FrameReply',
  full_name='FrameReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='FrameReply.reply', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['FrameRequest'] = _FRAMEREQUEST
DESCRIPTOR.message_types_by_name['FrameReply'] = _FRAMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameRequest = _reflection.GeneratedProtocolMessageType('FrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEREQUEST,
  '__module__' : 'video_frame_pb2'
  # @@protoc_insertion_point(class_scope:FrameRequest)
  })
_sym_db.RegisterMessage(FrameRequest)

FrameReply = _reflection.GeneratedProtocolMessageType('FrameReply', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEREPLY,
  '__module__' : 'video_frame_pb2'
  # @@protoc_insertion_point(class_scope:FrameReply)
  })
_sym_db.RegisterMessage(FrameReply)



_VIDEOFRAME = _descriptor.ServiceDescriptor(
  name='VideoFrame',
  full_name='VideoFrame',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=140,
  serialized_end=194,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='VideoFrame.Send',
    index=0,
    containing_service=None,
    input_type=_FRAMEREQUEST,
    output_type=_FRAMEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIDEOFRAME)

DESCRIPTOR.services_by_name['VideoFrame'] = _VIDEOFRAME

# @@protoc_insertion_point(module_scope)
