# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import video_frame_pb2 as video__frame__pb2


class VideoFrameStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.stream_stream(
        '/VideoFrame/Send',
        request_serializer=video__frame__pb2.FrameRequest.SerializeToString,
        response_deserializer=video__frame__pb2.FrameReply.FromString,
        )


class VideoFrameServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VideoFrameServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.stream_stream_rpc_method_handler(
          servicer.Send,
          request_deserializer=video__frame__pb2.FrameRequest.FromString,
          response_serializer=video__frame__pb2.FrameReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'VideoFrame', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
