version: "3.7"

services:
  # grpc-video-server-python:
  #   image: grpc-video-server-python
  #   build:
  #     context: .
  #     dockerfile: video-server-python/Dockerfile
  #   ports:
  #     - 50051:50051
  #   volumes:
  #     - videos:/src/videos

  # grpc-video-server-dotnetcore:
  #   image: grpc-video-server-dotnetcore
  #   build:
  #     context: .
  #     dockerfile: video-server-dotnetcore/Dockerfile
  #   ports:
  #     - "8080:80"
  #     - "44321:443"
  #     - "5001:5001"
  #   volumes:
  #     - videos:/src/videos

  # front:
  #   image: front
  #   build:
  #     context: .
  #     dockerfile: front/Dockerfile
  #   ports:
  #     - 3000:3000

  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net    
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

  # kafka-server2:
  #   image: 'bitnami/kafka:latest'
  #   networks:
  #     - kafka-net    
  #   ports:
  #     - '9093:9092'
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper-server



volumes:
  videos:

networks:
  kafka-net:
    driver: bridge
