version: "3.7"

services:
  grpc-video-server:
    image: grpc-video-server
    build:
      context: .
      dockerfile: video-server/Dockerfile
    ports:
      - 50051:50051
    volumes:
      - videos:/src/videos

volumes:
  videos:
