version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./Docker/Server.Dockerfile
    image: vid-stream-back:latest
    command: make run-server
    ports: 
      - 50051:50051
  
  py-client:
    build:
      context: .
      dockerfile: ./Docker/Client.Dockerfile
    image: vid-stream-client:latest
    network_mode: host
    command: make run-client
    restart: on-failure:10
    depends_on:
      - server
  
  js-client:
    build:
      context: ./vidview
      dockerfile: ./Docker/JS.Dockerfile
    image: vid-stream-js-client:latest
    command: npm start
    restart: always
    ports:
      - 3000:3000

  envoy:
    build:
      context: .
      dockerfile: ./Docker/Envoy.Dockerfile
    image: vid-stream-envoy
    ports:
      - 8080:8080
