version: "3.7"

services:
  grpc-video-server:
    image: grpc-video-server
    build:
      context: .
      dockerfile: video-server/Dockerfile
    ports:
      - 50051:50051
    volumes:
      - videos:/src/videos

  videoserverdotnetcore:
    image: ${DOCKER_REGISTRY-}videoserverdotnetcore
    build:
      context: .
      dockerfile: VideoServerDotNetCore/Dockerfile
    ports:
      - "8080:80"
      - "44321:443"
      - "5001:5001"

volumes:
  videos:
